# Generated by Django 4.0.4 on 2022-05-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.DateTimeField(verbose_name='Теги'),
        ),
    ]
