# Generated by Django 4.0.4 on 2022-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_alter_articles_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.CharField(max_length=50, verbose_name='Теги'),
        ),
    ]
